FROM fnndsc/ubuntu-python3:latest
LABEL maintainer = "Andrea Magan <andrea.magan@outlook.com>, Luis Lorenzo <luis.lorenzom@outlook.com>"

# Arguments
ARG CSRF_ENABLED
ARG DEBUG
ARG HOST
ARG PORT
ARG SQLALCHEMY_ECHO
ARG MIGRATION_PATH
ARG TRACK_MODIFICATIONS
ARG DATABASE_NAME
ARG DATABASE_PORT
ARG DATABASE_HOST
ARG DATABASE_PASSWORD
ARG DATABASE_USER
ARG JWT_SECRET_KEY
ARG MAIL_USERNAME
ARG MAIL_PASSWORD
ARG MAIL_SERVER
ARG MAIL_PORT
ARG MAIL_USE_SSL
ARG REDIS_PORT
ARG REDIS_HOST
ARG REDIS_PASSWORD
ARG SCOUTER_HOST
ARG SCOUTER_HOST
ARG SCOUTER_X_API_KEY

# Environment
ENV LANG C.UTF-8

ENV CSRF_ENABLED=${CSRF_ENABLED}
ENV DEBUG=${DEBUG}
ENV HOST=${HOST}
ENV PORT=${PORT}
ENV SQLALCHEMY_ECHO=${SQLALCHEMY_ECHO}
ENV MIGRATION_PATH=${MIGRATION_PATH}
ENV TRACK_MODIFICATIONS=${TRACK_MODIFICATIONS}
ENV DATABASE_NAME=${DATABASE_NAME}
ENV DATABASE_PORT=${DATABASE_PORT}
ENV DATABASE_HOST=${DATABASE_HOST}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV DATABASE_USER=${DATABASE_USER}
ENV JWT_SECRET_KEY=${JWT_SECRET_KEY}
ENV MAIL_USERNAME=${MAIL_USERNAME}
ENV MAIL_PASSWORD=${MAIL_PASSWORD}
ENV MAIL_SERVER=${MAIL_SERVER}
ENV MAIL_PORT=${MAIL_PORT}
ENV MAIL_USE_SSL=${MAIL_USE_SSL}
ENV REDIS_PORT=${REDIS_PORT}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV SCOUTER_HOST=${SCOUTER_HOST}
ENV SCOUTER_HOST=${SCOUTER_HOST}
ENV SCOUTER_X_API_KEY=${SCOUTER_X_API_KEY}

# Update and install system requirements
RUN apt-get update && apt-get -y install libpq-dev

# Upgrade pip
RUN pip install --upgrade pip

# Download Source Code
WORKDIR /home/amarrau/
ENV HOME /home/amarrau
COPY . ${HOME}

# Install python dependencies
RUN pip install -r requirements.txt

# Define entrypoint
ENTRYPOINT ["python3.6", "app.py"]
