name: CD/CI
on:
    push:
        branches:
            - master
    pull_request:
        branches:
          - master
jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
        - name: Check out Git repository
          uses: actions/checkout@v1
        - name: Set up Python3 environment
          uses: actions/setup-python@v1
          with:
            python-version: '3.7.6'
            architecture: 'x64'
        - name: Install pip dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run test
          env:
            DATABASE_TEST_URI: ${{ secrets.DATABASE_TEST_URI }}
          run: |
            python test_runner.py
        - name: Migrate database schema
          if: github.event_name != 'pull_request'
          env:
            DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
            DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
            DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
            DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
            DATABASE_USER: ${{ secrets.DATABASE_USER }}
          run: |
            flask db upgrade
        - name: Build Docker Image
          if: github.event_name != 'pull_request'
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            APP_NAME: ${{ 'amarrau' }}
          run: |
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            heroku container:push web -a $APP_NAME
        - name: Deploy Docker container
          if: github.event_name != 'pull_request'
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            APP_NAME: ${{ 'amarrau' }}
          run: |
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            heroku container:release web -a $APP_NAME
